"""empty message

Revision ID: 038d9d27f01f
Revises: e2a9bdd63ba3
Create Date: 2022-08-11 10:53:10.742910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038d9d27f01f'
down_revision = 'e2a9bdd63ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('has_type', sa.Enum('draft', 'show', name='postpublishtype'), server_default='show', nullable=False))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'has_type')
    # ### end Alembic commands ###
