"""empty message

Revision ID: 885ae77f91af
Revises: 038d9d27f01f
Create Date: 2022-08-11 10:58:07.939481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885ae77f91af'
down_revision = '038d9d27f01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('add_date', sa.DateTime(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=320), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_table('user')
    # ### end Alembic commands ###
